### PR TITLE
Fixed duplicate messages

### PR DESCRIPTION
**Pull request by Ahosall**
# Fixed duplicate messages

The following modifications had to be made:

- Pass the value `true` in the `edited` parameter in the `onMessageUpdate` function (`client:33:41`)
   ```diff
   - this.mirrorMessage(newMessage);
   + this.mirrorMessage(newMessage, true);
   ```
- Add edited parameter in the `mirrorMessage` function (`client.ts:37:44`)
   ```diff
   - private mirrorMessage(message: Message)
   + private mirrorMessage(message: Message, edited: boolean = false)
   ```
- Forward `edited` parameter to `dispatchMessage` (`client.ts:52:29`)
   ```diff
   - mirror.dispatchMessage(message, () => this.logMirroredMessage(message));
   + mirror.dispatchMessage(message, () => this.logMirroredMessage(message), edited);
   ```
- Create a private property in the `Mirror` class called `messagesSended` (`mirror.ts:74:4`)
   ```diff
   + private messagesSended: Array<{from: Message, to: string}> = [];
   ```
- Add extra parameter in the `dispatchMessage` function (`mirror.ts:116:83`)
   ```diff
   - public dispatchMessage(message: Message, callback: (message: Message) => void): void
   + public dispatchMessage(message: Message, callback: (message: Message) => void, edited: boolean = false): void
   ```
- Create a variable called `findMessage` to search for the sent message that will be updated (`mirror.ts:119:12`)
   ```diff
   + const findMessage = this.messagesSended.filter((m) => m.from.id === message.id);
   ```
- Create logic to check whether the message is edited and whether this message was found. If the message is edited and found, it triggers the `editMessage` function, if it was not edited or found, it triggers the `send` function of the `webhook`, if the sending is successful, it stores the edited message and the `id` of the message. message sent by the `webhook`, immediately after the message received in the `callback` is sent (`mirror.ts:123:12`)
   ```diff
  - webhook
  -   .send(payload)
  -   .then(() => callback(message))
  -   .catch(error => console.log(error));
  + try {
  +   if (edited && findMessage.length > 0) {
  +     webhook.editMessage(findMessage[0].to, payload);
  +   } else {
  +     webhook.send(payload).then((whMsg) => {
  +       this.messagesSended.push({
  +         from: message,
  +         to: whMsg.id,
  +       });
  +     });
  +   }
  +   callback(message);
  + } catch (error) {
  +   console.log(error);
  + }
  ```

Finally, that's it, any questions, I'm at your disposal.

My contact:
- Discord: [ahos.all](https://discord.com/channels/@me/683703998729027769)

### CODE REVIEW

**Comment by louanfontenele** [comment]
Thanks bro.

**Comment by isoyand** [comment]
can you add the ability to mirror forums/threads?

**Comment by crimilo** [comment]
> can you add the ability to mirror forums/threads?

you already can. pull the latest version from github and configure a forum/thread id instead of a regular channel id.

**Comment by isoyand** [comment]
> > can you add the ability to mirror forums/threads?
> 
> you already can. pull the latest version from github and configure a forum/thread id instead of a regular channel id.

tested now, it doesn't work

**Comment by isoyand** [comment]
> > can you add the ability to mirror forums/threads?
> 
> you already can. pull the latest version from github and configure a forum/thread id instead of a regular channel id.

can we just put forum id amd script will be mirroring all messages from all threads in forum channel? if not, it would be great to add it.

**Pull request closed without merging**
